### ISSUE TITLE
issue: How to set charge resume level?

### ISSUE THREAD

**Issue by Aurosutru** [tshakalekholoane/bat#21]
Hi,

This app is working nicely on an Asus M15 laptop running Fedora 34.

I have set the upper charge threshold at 60% and am wondering at what point charging will resume.  One battery manager uses a low 30% figure for resuming charging and another uses 58%.  Is there a way to adjust the resume charging level using bat?

BTW, the Fedora charging indicator correctly shows "Not Charging" when battery is above 60% charge.

Thanks.

**Comment by tshakalekholoane** [comment]
> Is there a way to adjust the resume charging level using bat?

No, there is no way to adjust the resume charging level using bat. All it does is set the threshold level.

**Comment by Aurosutru** [comment]
Does the charging resume as soon as the battery level goes below 60%, or whatever number is set as the  threshold?

**Comment by tshakalekholoane** [comment]
Yes, that is the default behaviour on most systems.
