### ISSUE TITLE
issue: Fails to build: cannot load embed: malformed module path "embed"

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [tshakalekholoane/bat#22]
`go build ./cmd/bat/` results in 

>     build tshaka.co/bat/cmd/bat: cannot load embed: malformed module path "embed": missing dot in first path element

Steps to reproduce on Ubuntu 20.04:
```bash
cd ~/dev
git clone https://github.com/tshakalekholoane/bat.git
cd bat
sudo apt install golang-go
time go build ./cmd/bat/
```

output:
```bash
~/GS/dev/bat$ time go build ./cmd/bat/
build tshaka.co/bat/cmd/bat: cannot load embed: malformed module path "embed": missing dot in first path element
```

And a slightly different attempt (seems to have resolved the error above, but now results in a new one):
```bash
~/GS/dev/bat$ time go build cmd/bat/
can't load package: package cmd/bat: package cmd/bat is not in GOROOT (/usr/lib/go-1.13/src/cmd/bat)
```

**Comment by tshakalekholoane** [comment]
Which version of Go are you running?

**Comment by ElectricRCAircraftGuy** [comment]
> Which version of Go are you running?

```bash
$ go version
go version go1.13.8 linux/amd64
```

**Comment by tshakalekholoane** [comment]
Embedded files were only introduced in [Go 1.16](https://go.dev/doc/go1.16#library-embed). Try with a version later than that if you  prefer building over grabbing a binary from the releases page.
