### ISSUE TITLE
Works with T14 Gen2 Intel ThinkPads

### ISSUE THREAD

**Issue by Midnex** [tshakalekholoane/bat#24]
### Subject of the issue

Just wanted to add that the T14 Gen2 Intel version also works with this.

### Your system

For example,

OS: Manjaro Linux x86_64
Host: 20W0003KUS ThinkPad T14 Gen 2i
Kernel: 5.15.12-1-MANJARO
CPU: Intel i5-1135G7 11th Gen

### Version

0.8.4 (Latest)

**Comment by tshakalekholoane** [comment]
Great! Thank you for letting me know.
