### ISSUE TITLE
issue: bat uninstall

### ISSUE THREAD

**Issue by batgithubpf** [tshakalekholoane/bat#25]
### Subject of the issue

Bat is easy to install and works fine in ubuntu/asus: how to uninstall it?

### Your system

OS:  Ubuntu 22.04 Linux x86_64
Host: ZenBook 
Kernel: 5.15.0-27-generic

### Version

0.8.4 (Latest)

**Comment by tshakalekholoane** [comment]
Just delete the `bat` file.

**Comment by batgithubpf** [comment]
Not so simple!

-------- Message initial --------
De: Tshaka Eric Lekholoane ***@***.***>
Répondre à: tshakalekholoane/bat
***@***.***>
À: tshakalekholoane/bat ***@***.***>
Cc: batgithubpf ***@***.***>, Author
***@***.***>
Objet: Re: [tshakalekholoane/bat] issue: bat uninstall (Issue #25)
Date: Tue, 26 Apr 2022 11:14:30 -0700

Just delete the bat file.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by gamegine** [comment]
run --reset first to remove the changes introduced by --persist and then remove the executable bat file

**Comment by batgithubpf** [comment]
It's OK, thank you.

-------- Message initial --------
De: gamegine ***@***.***>
Répondre à: tshakalekholoane/bat
***@***.***>
À: tshakalekholoane/bat ***@***.***>
Cc: batgithubpf ***@***.***>, Author
***@***.***>
Objet: Re: [tshakalekholoane/bat] issue: bat uninstall (Issue #25)
Date: Wed, 27 Apr 2022 00:31:01 -0700

run --reset first to remove the changes introduced by --persist and
then remove the executable bat file
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by tshakalekholoane** [comment]
Did that solve the problem? Running the following as @gamegine suggested is usually enough since the entire application is contained in a single binary but I could be missing something.

```
bat --reset && rm bat
```

**Comment by batgithubpf** [comment]
Yes thank you, seems to have solved the problem.
-------- Message initial --------
De: Tshaka Eric Lekholoane ***@***.***>
Répondre à: tshakalekholoane/bat
***@***.***>
À: tshakalekholoane/bat ***@***.***>
Cc: batgithubpf ***@***.***>, Author
***@***.***>
Objet: Re: [tshakalekholoane/bat] issue: bat uninstall (Issue #25)
Date: Wed, 27 Apr 2022 05:47:35 -0700

Did that solve the problem? Running the following as @gamegine
suggested is usually enough since the entire application is contained
in a single binary but I could be missing something.
bat --reset && rm bat
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID:
***@***.***>
