### ISSUE TITLE
issue: Could not find Bash on NixOS while setting persist mode

### ISSUE THREAD

**Issue by igor-frolikov** [tshakalekholoane/bat#26]
### Subject of the issue

[igor@nixos:~]$ sudo bat -t 80
Charging threshold set.
Use `sudo bat --persist` to persist the setting between restarts.

[igor@nixos:~]$ sudo bat -p
Could not find Bash on your system.

NixOS uses Bash as default shell. Please, check your shell calls. Setting threshold works fine.

### Your system

OS: NixOS 22.05 (Quokka) x86_64
Host: ASUSTeK COMPUTER INC. X513IA 
Kernel: 5.15.43 

### Version

0.9 (Latest)

**Comment by igor-frolikov** [comment]
It seems? that you need to add  another bash path to your services.go: "/run/current-system/sw/bin/"

**Comment by tshakalekholoane** [comment]
Thank you for pointing that out, @igor-frolikov. I think it has to be the full path because some of these are run before path variables are set. But that said, there is probably a better way to set it. Can you check if running `command -v bash` gives the right location for Bash on your system?

**Comment by igor-frolikov** [comment]
[igor@nixos:~]$ command -v bash
/run/current-system/sw/bin/bash

**Comment by tshakalekholoane** [comment]
Here's a [fix](https://github.com/tshakalekholoane/bat/files/8881127/bat.zip). Please let me know if it works.

**Comment by igor-frolikov** [comment]
[igor@nixos:~/Downloads]$ sudo ./bat -c
100

[igor@nixos:~/Downloads]$ sudo ./bat -t 60
Charging threshold set.
Use `sudo bat --persist` to persist the setting between restarts.

[igor@nixos:~/Downloads]$ sudo ./bat -c
100

[igor@nixos:~/Downloads]$ sudo ./bat -p
2022/06/10 23:14:33 open /etc/systemd/system/bat-suspendthenhibernate.service: read-only file system

Actually NixOS would never allow to write to system files. Thank you for your efforts. I wrote a simple script for cron. Works perfect even on Arch. Just on NixOS I run cron job using NixOS way.
