### ISSUE TITLE
Not working. After connect charger battery charging. ASUS TUF Gaming F17 FX706HE_FX706HE 1.0 

### ISSUE THREAD

**Issue by electro-nic** [tshakalekholoane/bat#28]
### Subject of the issue

Not working. After connect charger battery charging.  
┌──(root㉿kali-[/sys/class/power_supply]
└─# ls         
ACAD  BAT1
                                                                                                                
┌──(root㉿kali-[/sys/class/power_supply]
└─# ls -l
загалом 0
lrwxrwxrwx 1 root root 0 чер 25 16:08 ACAD -> ../../devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0003:00/power_supply/ACAD                                                                                                               
lrwxrwxrwx 1 root root 0 чер 25 16:06 BAT1 -> ../../devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0A:00/power_supply/BAT1
                                                                                                                
┌──(root㉿kali-[/sys/class/power_supply]
└─# ls -l
загалом 0
lrwxrwxrwx 1 root root 0 чер 25 16:08 ACAD -> ../../devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0003:00/power_supply/ACAD
lrwxrwxrwx 1 root root 0 чер 25 16:06 BAT1 -> ../../devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0A:00/power_supply/BAT1
                                                                                                                                                                    
┌──(root㉿kali-[/sys/class/power_supply]
└─# cd /sys/class/power_supply/BAT1 
                                                                                                                                                                    
┌──(root㉿kali-[/sys/class/power_supply/BAT1]
└─# ls -a
.      capacity                      charge_full         current_now  hwmon1        power          status      type                voltage_now
..     capacity_level                charge_full_design  cycle_count  manufacturer  present        subsystem   uevent
alarm  charge_control_end_threshold  charge_now          device       model_name    serial_number  technology  voltage_min_design
                                                                                                                                                                    
┌──(root㉿kali-[/sys/class/power_supply/BAT1]
└─# ls -l
загалом 0
-rw-r--r-- 1 root root 4096 чер 26 08:52 alarm
-r--r--r-- 1 root root 4096 чер 25 16:08 capacity
-r--r--r-- 1 root root 4096 чер 26 08:52 capacity_level
-rw-r--r-- 1 root root 4096 чер 26 08:34 charge_control_end_threshold
-r--r--r-- 1 root root 4096 чер 25 16:08 charge_full
-r--r--r-- 1 root root 4096 чер 25 16:08 charge_full_design
-r--r--r-- 1 root root 4096 чер 25 16:08 charge_now
-r--r--r-- 1 root root 4096 чер 25 16:08 current_now
-r--r--r-- 1 root root 4096 чер 25 16:08 cycle_count
lrwxrwxrwx 1 root root    0 чер 26 00:27 device -> ../../../PNP0C0A:00
drwxr-xr-x 3 root root    0 чер 25 19:06 hwmon1
-r--r--r-- 1 root root 4096 чер 25 16:08 manufacturer
-r--r--r-- 1 root root 4096 чер 25 16:08 model_name
drwxr-xr-x 2 root root    0 чер 26 08:52 power
-r--r--r-- 1 root root 4096 чер 25 16:08 present
-r--r--r-- 1 root root 4096 чер 25 16:08 serial_number
-r--r--r-- 1 root root 4096 чер 25 16:08 status
lrwxrwxrwx 1 root root    0 чер 25 16:06 subsystem -> ../../../../../../class/power_supply
-r--r--r-- 1 root root 4096 чер 25 16:08 technology
-r--r--r-- 1 root root 4096 чер 25 16:08 type
-rw-r--r-- 1 root root 4096 чер 25 17:14 uevent
-r--r--r-- 1 root root 4096 чер 25 16:08 voltage_min_design
-r--r--r-- 1 root root 4096 чер 25 16:08 voltage_now
                                                                                                                                                                    
┌──(root㉿kali-[/sys/class/power_supply/BAT1]
└─# cat /sys/class/power_supply/BAT1/status
Charging
                                                                                                                                                                    
┌──(root㉿kali-[/sys/class/power_supply/BAT1]
└─# cat /sys/class/power_supply/BAT1/capacity
76
                                                                                                                                                                    
┌──(root㉿kali-[/sys/class/power_supply/BAT1]
└─# cat /sys/class/power_supply/BAT1/charge_control_end_threshold 
50
                                                                                                                                                                    
┌──(root㉿kali-[/sys/class/power_supply/BAT1]
└─# echo 60 > /sys/class/power_supply/BAT1/charge_control_end_threshold
                                                                                                                                                                    
┌──(root㉿kali-[/sys/class/power_supply/BAT1]
└─# cat /sys/class/power_supply/BAT1/status                            
Unknown

If i take this command charging stopped

### Your system

OS: Kali GNU/Linux Rolling x86_64
Host: ASUS TUF Gaming F17 FX706HE_FX706HE 1.0 
Kernel: Linux 11 5.17.0-kali3-amd64 #1 SMP PREEMPT Debian 5.17.11-1kali1 (2022-05-30) x86_64 GNU/Linux
└─# bat -v
bat 0.9.1

### Version

0.9.1 (Latest)

**Comment by tshakalekholoane** [comment]
So if I understand you correctly, when you run `echo 60 > /sys/class/power_supply/BAT1/charge_control_end_threshold` it works but when you run `bat -t 60` it does not?
