### ISSUE TITLE
issue: when i run " # ./bat --threshold"

### ISSUE THREAD

**Issue by hideandseekstheorder** [tshakalekholoane/bat#40]
### Subject of the issue

There is no --threshold option. Run `bat --help` to see a list of available options.

### Your system

.............                                    
            ..,;:ccc,.                             ------------------- 
          ......''';lxO.                           OS: Kali GNU/Linux Rolling x 
.....''''..........,:ld;                          
           .';;;:::;,,.x,                          Kernel: 5.18.0-kali7-amd64 
      ..'''.            0Xxoc:,.  ...              Uptime: 42 mins 
  ....                ,ONkc;,;cokOdc',.            Packages: 5479 (dpkg), 15 (s 
 .                   OMo           ':ddo.          Shell: zsh 5.9 
                    dMc               :OO;         Resolution: 1366x768 
                    0M.                 .:o.       DE: GNOME 43.0 
                    ;Wd                            WM: Mutter 
                     ;XO,                          WM Theme: Kali-Dark 
                       ,d0Odlc;,..                 Theme: adw-gtk3-dark [GTK2/3 
                           ..',;:cdOOd::,.         Icons: Flat-Remix-Blue-Dark  
                                    .:d;.':;.      Terminal: gnome-terminal 
                                       'd,  .'     
                                         ;l   ..   
                                          .o       
                                            c    

### Version

0.10.1 (Latest)

**Comment by tshakalekholoane** [comment]
The threshold flag was changed to a subcommand in version 0.10 so instead of `--threshold` it's just `threshold` now.
