### ISSUE TITLE
issue: 目前本人用thinkpad t15g gen1 移动工作站，以后可能换dell precision，请贵编以后加强下dell 

### ISSUE THREAD

**Issue by newyorkthink** [tshakalekholoane/bat#58]
### Subject of the issue

issue: 目前本人用thinkpad t15g gen1 移动工作站，以后可能换dell precision，请贵编以后加强下dell 

### Your system

For example,

OS: debian
Host: ZenBook UX425EA_UX425EA 1.0
Kernel: 5.13.8-1-MANJARO

### Version

0.12 (Latest)

**Comment by tshakalekholoane** [comment]
非常抱歉，除非我也换成戴尔笔记本电脑，否则很难加强对戴尔的关注。不过，我发现在以下链接的问题中，有人遇到了类似的问题：https://github.com/tshakalekholoane/bat/issues/4。你可以参考那个问题来了解更多信息。
